language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm (Symfony Process mustRun)
  - nightly

before_script:
  - chmod 777 Tests/tmp

  # Install p7zip
#  - sudo apt-get install p7zip-full
  - curl -L  http://downloads.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_src_all.tar.bz2 > p7zip_16.02_src_all.tar.bz2
  - tar xjvf p7zip_16.02_src_all.tar.bz2
  - cd p7zip_16.02
  - make all3
  - sudo ./install.sh
  - sudo ln /usr/local/bin/7za /usr/bin/7za
  - cd ..

  - composer self-update && composer install --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false
