language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
    # Install p7zip
    #  - sudo apt-get install p7zip-full
    - curl -L  http://downloads.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_src_all.tar.bz2 > p7zip_16.02_src_all.tar.bz2
    - tar xjvf p7zip_16.02_src_all.tar.bz2
    - cd p7zip_16.02
    - make all3
    - sudo ./install.sh
    - sudo ln /usr/local/bin/7za /usr/bin/7za
    - cd ..

    # Update composer
    - composer self-update
    - composer clear-cache

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
    - vendor/bin/phpunit --configuration phpunit.xml

notifications:
    email:
        on_failure: change
