language: php
php:
    - 7.3
    - 7.4
    - 8.0
    - nightly

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --ansi --no-progress --no-suggest --prefer-dist"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    # Install p7zip
    - curl -L https://github.com/jinfeihan57/p7zip/archive/v17.03.tar.gz > v17.03.tar.gz
    - tar xzvf v17.03.tar.gz
    - cd p7zip-17.03
    - make all3
    - sudo ./install.sh
    - sudo ln /usr/local/bin/7za /usr/bin/7za
    - sudo ln /usr/local/bin/7z /usr/bin/7z
    - cd ..

    - composer validate

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist

notifications:
    email:
        on_failure: change
